
MODEL (
  name lth_bronze.src_scr__care_plan_mdt,
  kind VIEW,
  cron '@daily',
);

select
  CARE_ID as care_id,
  [Cancer Site] collate SQL_Latin1_General_CP1_CI_AS as cancer_site,
  [NHS Number] collate SQL_Latin1_General_CP1_CI_AS as nhs_number,
  [Hospital Number] collate SQL_Latin1_General_CP1_CI_AS as mrn,
  [Care Plan Agreed Date] as care_plan_agreed_date,
  Organisation collate SQL_Latin1_General_CP1_CI_AS as organisation,
  [Cancer Care Plan Intent] collate SQL_Latin1_General_CP1_CI_AS as cancer_care_plan_intent,
  [First Treatment] collate SQL_Latin1_General_CP1_CI_AS as first_treatment,
  [Second Treatment] collate SQL_Latin1_General_CP1_CI_AS as second_treatment,
  [Third Treatment] collate SQL_Latin1_General_CP1_CI_AS as third_treatment,
  [Fourth Treatment] collate SQL_Latin1_General_CP1_CI_AS as fourth_treatment,
  [To be actioned by] collate SQL_Latin1_General_CP1_CI_AS as to_be_actioned_by,
  [Performance Status] collate SQL_Latin1_General_CP1_CI_AS as performance_status,
  [Co-morbidity Index] collate SQL_Latin1_General_CP1_CI_AS as comorbidity_index,
  [Was patient discussed at MDT] collate SQL_Latin1_General_CP1_CI_AS as was_patient_discussed_mdt,
  [MDT Meeting Site] collate SQL_Latin1_General_CP1_CI_AS as mdt_meeting_site,
  [Sub Site] collate SQL_Latin1_General_CP1_CI_AS as sub_site,
  [MDT Meeting Date] as mdt_meeting_date,
  Location collate SQL_Latin1_General_CP1_CI_AS as location,
  [Was Care Plan Agreed at MDT] collate SQL_Latin1_General_CP1_CI_AS as care_plan_agreed_mdt,
  cast([MDT Comments] collate SQL_Latin1_General_CP1_CI_AS as varchar(150)) as mdt_comments,
  [Referred To] collate SQL_Latin1_General_CP1_CI_AS as referred_to,
  [Who Referred To] collate SQL_Latin1_General_CP1_CI_AS as who_referred_to,
  [Reviewed by Pathologist prior to MDT] collate SQL_Latin1_General_CP1_CI_AS as reviewed_pathologist_before_mdt,
  [Reviewed By] collate SQL_Latin1_General_CP1_CI_AS as reviewed_by,
  [No Treatment Reason] collate SQL_Latin1_General_CP1_CI_AS as no_treatment_reason,
  [Was patient discussed at Network MDT] collate SQL_Latin1_General_CP1_CI_AS as discussed_network_mdt,
  [Date of Network Meeting] as date_network_meeting,
  cast([Network Decision] as varchar(150)) collate SQL_Latin1_General_CP1_CI_AS as network_decision,
  [Network To be actioned by] collate SQL_Latin1_General_CP1_CI_AS as network_to_be_actioned_by,
  cast([Network Comments] as varchar(150)) collate SQL_Latin1_General_CP1_CI_AS as network_comments,
  [eGFR Status requested?] collate SQL_Latin1_General_CP1_CI_AS as egfr_requested_status,
  [Was Resective Pathology Discussed?] collate SQL_Latin1_General_CP1_CI_AS as resective_path_discussed,
  [Restorative Dentist asked if Restorative Assessment Needed?] collate SQL_Latin1_General_CP1_CI_AS
    as restorative_dentist_asked_assessment_needed,
  [Restorative dental assessment necessary?] collate SQL_Latin1_General_CP1_CI_AS
    as restorative_dentist_assessment_needed,
  [Discussion Type] collate SQL_Latin1_General_CP1_CI_AS as discussion_type,
  getdate() as last_edit_time,
  getdate() as updated_at,
  'rxn' collate SQL_Latin1_General_CP1_CI_AS as org_code,
  'scr' collate SQL_Latin1_General_CP1_CI_AS as source_system
from @scr_db.dbo.BIvwCarePlanMDT