
MODEL (
  name lth_bronze.src_scr__referrals,
  kind VIEW,
  cron '@daily',
);

select
  CARE_ID as care_id,
  [Patient ID] as patient_id_scr,
  [Cancer Site] collate SQL_Latin1_General_CP1_CI_AS as cancer_site,
  Subtype collate SQL_Latin1_General_CP1_CI_AS as subtype,
  [NHS Number] collate SQL_Latin1_General_CP1_CI_AS as nhs_number,
  [Hospital Number] collate SQL_Latin1_General_CP1_CI_AS as mrn,
  [Source of Referral] collate SQL_Latin1_General_CP1_CI_AS as source_of_referral,
  [Priority Type] collate SQL_Latin1_General_CP1_CI_AS as priority_type,
  [Referral Route] collate SQL_Latin1_General_CP1_CI_AS as referral_route,
  [Other Route] collate SQL_Latin1_General_CP1_CI_AS as other_route,
  [Rapid Diagnostic Centre Pathway] collate SQL_Latin1_General_CP1_CI_AS as rapid_diagnostic_cancer_pathway,
  [Upgrade Date] as upgrade_date,
  [Referral Type] collate SQL_Latin1_General_CP1_CI_AS as referral_type,
  [GP Code] collate SQL_Latin1_General_CP1_CI_AS as gp_code,
  [GP Name] collate SQL_Latin1_General_CP1_CI_AS as gp_name,
  [Practice Code] collate SQL_Latin1_General_CP1_CI_AS as practice_code,
  [Branch Code] collate SQL_Latin1_General_CP1_CI_AS as branch_code,
  CCG collate SQL_Latin1_General_CP1_CI_AS as ccg,
  [CCG Code] collate SQL_Latin1_General_CP1_CI_AS as ccg_code,
  [Patient Status] collate SQL_Latin1_General_CP1_CI_AS as patient_status,
  [Date Decision to Refer] as date_decision_to_refer,
  [Date Receipt of Referral] as date_receipt_of_referral,
  [Date First Appointment] as date_first_appointment,
  [Was this the first appt offered] collate SQL_Latin1_General_CP1_CI_AS as first_appt_offered,
  [Reason No Appointment] collate SQL_Latin1_General_CP1_CI_AS as reason_no_appt,
  Organisation collate SQL_Latin1_General_CP1_CI_AS as organsiation,
  [Consultant (First Appointment)] collate SQL_Latin1_General_CP1_CI_AS as cons_first_appt,
  [Was initial referral made to appropriate specialist]
    collate SQL_Latin1_General_CP1_CI_AS as initial_ref_appropriate_specialist,
  [First Appointment Type] collate SQL_Latin1_General_CP1_CI_AS as first_appt_type,
  [Date Referred to Specialist] as date_referred_to_specialist,
  [Organisation (Referred From)] collate SQL_Latin1_General_CP1_CI_AS as org_referred_from,
  [Date First Appt with Specialist] as date_first_appt_specialist,
  [Organisation (First Appt Specialist)] collate SQL_Latin1_General_CP1_CI_AS as org_first_appt_specialist,
  Consultant collate SQL_Latin1_General_CP1_CI_AS as consultant,
  Specialty collate SQL_Latin1_General_CP1_CI_AS as specialty,
  cast([NICE Referring symptoms] collate SQL_Latin1_General_CP1_CI_AS as varchar(200)) collate SQL_Latin1_General_CP1_CI_AS as nice_referring_symptoms,
  cast([Referring Symptoms] collate SQL_Latin1_General_CP1_CI_AS as varchar(200)) collate SQL_Latin1_General_CP1_CI_AS as referring_symptoms,
  cast([Other Symptoms] collate SQL_Latin1_General_CP1_CI_AS as varchar(200)) collate SQL_Latin1_General_CP1_CI_AS as other_symptoms,
  cast([Method of Referral] collate SQL_Latin1_General_CP1_CI_AS as varchar(50)) collate SQL_Latin1_General_CP1_CI_AS as method_of_referral,
  [Appropriateness of Referral] collate SQL_Latin1_General_CP1_CI_AS as appropriateness_of_ref,
  cast([Reason Inappropriate] collate SQL_Latin1_General_CP1_CI_AS as varchar(200)) collate SQL_Latin1_General_CP1_CI_AS as reason_inappropriate,
  cast([Additional Comments] collate SQL_Latin1_General_CP1_CI_AS as varchar(200)) collate SQL_Latin1_General_CP1_CI_AS as additional_comments,
  [Date DNA Appt Re-Booked] as date_dna_appt_rebooked,
  cast([Adjustment Reason] collate SQL_Latin1_General_CP1_CI_AS as varchar(200)) collate SQL_Latin1_General_CP1_CI_AS as adjustment_reason,
  [Waiting Time Adj] as waiting_time_adjust,
  cast([Delay Reason] collate SQL_Latin1_General_CP1_CI_AS as varchar(200)) collate SQL_Latin1_General_CP1_CI_AS as delay_reason,
  cast([Delay Reason Comments] collate SQL_Latin1_General_CP1_CI_AS as varchar(200)) collate SQL_Latin1_General_CP1_CI_AS as delay_reason_comments,
  [Waiting Time Adj DTT (Days)] as waiting_time_adj_dtt_days,
  cast([ADT Referral ID] collate SQL_Latin1_General_CP1_CI_AS as varchar(50)) collate SQL_Latin1_General_CP1_CI_AS as adt_ref_id,
  cast([Referring Organisation] collate SQL_Latin1_General_CP1_CI_AS as varchar(200)) collate SQL_Latin1_General_CP1_CI_AS as ref_org,
  cast([Validated For Upload] collate SQL_Latin1_General_CP1_CI_AS as varchar(3)) collate SQL_Latin1_General_CP1_CI_AS as val_for_upload,
  getdate() as last_edit_time,
  getdate() as updated_at,
  'rxn' collate SQL_Latin1_General_CP1_CI_AS as org_code,
  'scr' collate SQL_Latin1_General_CP1_CI_AS as source_system
from @scr_db.dbo.BIvwReferrals
