
MODEL (
  name lth_bronze.src_scr__cosd,
  kind VIEW,
  cron '@daily',
);

select
  CARE_ID as care_id,
  [Hospital Number] collate SQL_Latin1_General_CP1_CI_AS as mrn,
  [NHS Number] collate SQL_Latin1_General_CP1_CI_AS as nhs_number,
  [Cancer Site] collate SQL_Latin1_General_CP1_CI_AS as cancer_site,
  [ICD10 Code] collate SQL_Latin1_General_CP1_CI_AS as icd_code,
  [Diagnosis (SNOMED)] as snomed_diagnosis,
  [Date of Diagnosis] as diagnosis_date,
  [Basis of Diagnosis] collate SQL_Latin1_General_CP1_CI_AS as diagnosis_basis,
  [Organisation (Diagnosis)] collate SQL_Latin1_General_CP1_CI_AS as diagnosis_organisation,
  [Performance Status] collate SQL_Latin1_General_CP1_CI_AS as performance_status,
  [Pre Treatment T Stage] collate SQL_Latin1_General_CP1_CI_AS as t_stage_pre_treatment,
  [Pre Treatment N Stage] collate SQL_Latin1_General_CP1_CI_AS as n_stage_pre_treatment,
  [Pre Treatment M Stage] collate SQL_Latin1_General_CP1_CI_AS as m_stage_pre_treatment,
  [Pre-Treatment Staging] collate SQL_Latin1_General_CP1_CI_AS as staging_pre_treatment,
  [Pre Treatment TNM Grouping] collate SQL_Latin1_General_CP1_CI_AS as tnm_group_pre_treatment,
  [Pre Treatment TNM Date] as tnm_date_pre_treatment,
  [Final T Stage] collate SQL_Latin1_General_CP1_CI_AS as t_stage_final,
  [Final N Stage] collate SQL_Latin1_General_CP1_CI_AS as n_stage_final,
  [Final M Stage] collate SQL_Latin1_General_CP1_CI_AS as m_stage_final,
  [Final Staging] collate SQL_Latin1_General_CP1_CI_AS as staging_final,
  [Final TNM Stage Grouping] collate SQL_Latin1_General_CP1_CI_AS as tnm_group_final,
  [Final TNM Stage Date] as tnm_date_final,
  [FIGO Stage] collate SQL_Latin1_General_CP1_CI_AS as figo_stage,
  [FIGO Letter] collate SQL_Latin1_General_CP1_CI_AS as figo_letter,
  [FIGO Number] collate SQL_Latin1_General_CP1_CI_AS as figo_number,
  [Ann Arbor Stage] collate SQL_Latin1_General_CP1_CI_AS as ann_arbor_stage,
  [Ann Arbor Symptoms] collate SQL_Latin1_General_CP1_CI_AS as ann_arbor_symptoms,
  [Ann Arbor Extranodality] collate SQL_Latin1_General_CP1_CI_AS as ann_arbor_extranodality,
  [Ann Arbor Bulk] collate SQL_Latin1_General_CP1_CI_AS as ann_arbor_bulk,
  [Binet Stage] collate SQL_Latin1_General_CP1_CI_AS as binet_stage,
  [Murphy (St Jude) Stage] collate SQL_Latin1_General_CP1_CI_AS as murphy_st_jude_stage,
  [Wilms Tumour Stage] collate SQL_Latin1_General_CP1_CI_AS as wilms_tumour_stage,
  [RMH Stage Grouping] collate SQL_Latin1_General_CP1_CI_AS as rmh_stage_group,
  [Barcelona Clinic Liver Cancer Stage] collate SQL_Latin1_General_CP1_CI_AS as barcelona_clinic_liver_cancer_stage,
  [R-ISS Stage] as r_iss_stage,
  [CNS Seen by Indicator Code] collate SQL_Latin1_General_CP1_CI_AS as cns_seen_indicator_code,
  getdate() as last_edit_time,
  getdate() as updated_at, 
  'rxn' collate SQL_Latin1_General_CP1_CI_AS as org_code,
  'scr' collate SQL_Latin1_General_CP1_CI_AS as source_system
from @scr_db.dbo.BIvwCOSDKeyItems
