
MODEL (
  name lth_bronze.src_scr__brachytherapy,
  kind VIEW,
  cron '@daily',
);

select 
  [CARE_ID] as care_id,
  [Cancer Site] collate SQL_Latin1_General_CP1_CI_AS as cancer_site,
  [NHS Number] collate SQL_Latin1_General_CP1_CI_AS as nhs_number,
  [Hospital Number] collate SQL_Latin1_General_CP1_CI_AS as mrn,
  [Consultant] collate SQL_Latin1_General_CP1_CI_AS as consultant,
  [Date Decision to Treat] collate SQL_Latin1_General_CP1_CI_AS as date_decision_to_treat,
  [Organisation (DTT)] collate SQL_Latin1_General_CP1_CI_AS as organisation_dtt,
  [Date Start of Treatment] collate SQL_Latin1_General_CP1_CI_AS as date_treatment_start,
  [Organisation (Treatment) Site Code] collate SQL_Latin1_General_CP1_CI_AS as organisation_site_code,
  [Organisation (Treatment) Name] collate SQL_Latin1_General_CP1_CI_AS as organisation_name,
  [Treatment Event Type] collate SQL_Latin1_General_CP1_CI_AS as treatment_event_type,
  [Treatment Setting] collate SQL_Latin1_General_CP1_CI_AS as treatment_setting,
  [Clinical Trial] collate SQL_Latin1_General_CP1_CI_AS as clinical_trial,
  [Treatment Intent] collate SQL_Latin1_General_CP1_CI_AS as treatment_intent,
  [Adjunctive Therapy] collate SQL_Latin1_General_CP1_CI_AS as adjunctive_therapy,
  [Short/Long Course] collate SQL_Latin1_General_CP1_CI_AS as short_long_course,
  [Treatment Site] collate SQL_Latin1_General_CP1_CI_AS as treatment_site,
  [Anatomical Site] collate SQL_Latin1_General_CP1_CI_AS as anatomical_site,
  [Brachytherapy Type] collate SQL_Latin1_General_CP1_CI_AS as brachytherapy_type,
  [Isotope Type] collate SQL_Latin1_General_CP1_CI_AS as isotype_type,
  [Delivery Type] collate SQL_Latin1_General_CP1_CI_AS as delivery_type,
  [Anaesthetic Required] collate SQL_Latin1_General_CP1_CI_AS as anaesthetic_required,
  [Unsealed Source Pt Type] collate SQL_Latin1_General_CP1_CI_AS as insealed_source_pt_type,
  [Prescribed Dose (Gy)] as prescribed_dose,
  [Prescribed Duration] as prescribed_duration,
  [Prescribed Fractions] as prescribed_functions,
  [Actual Dose (Gy)] as actual_dose,
  [Actual Duration] as actual_duration,
  [No of Insertions] as no_of_insertions,
  [Dose per Insertion] as dose_per_insertion,
  [Dose Rate] collate SQL_Latin1_General_CP1_CI_AS as dose_rate,
  [Treatment Outcome] collate SQL_Latin1_General_CP1_CI_AS as treatment_outcome,
  [End Date] collate SQL_Latin1_General_CP1_CI_AS as end_date,
  getdate() as last_edit_time,
  getdate() as updated_at,
  'rxn' collate SQL_Latin1_General_CP1_CI_AS as org_code,
  'scr' collate SQL_Latin1_General_CP1_CI_AS as source_system
from @scr_db.dbo.BIvwTreatmentBrachytherapy
