
MODEL (
  name lth_bronze.src_scr__investigations,
  kind VIEW,
  cron '@daily',
);

select
  CARE_ID as care_id,
  [Cancer Site] collate SQL_Latin1_General_CP1_CI_AS as cancer_site,
  [NHS Number] collate SQL_Latin1_General_CP1_CI_AS as nhs_number,
  [Hospital Number] collate SQL_Latin1_General_CP1_CI_AS as mrn,
  [Diagnostic Investigation] collate SQL_Latin1_General_CP1_CI_AS as diagnostic_investigation,
  [Other Investigation] collate SQL_Latin1_General_CP1_CI_AS as other_investigation,
  [Date Requested] as date_requested,
  [Requested By] collate SQL_Latin1_General_CP1_CI_AS as requested_by,
  Organisation collate SQL_Latin1_General_CP1_CI_AS as organisation,
  [Anaesthesia Required] collate SQL_Latin1_General_CP1_CI_AS as anaesthesia_required,
  [Pre-Booked Investigation] collate SQL_Latin1_General_CP1_CI_AS as pre_booked_investigation,
  [Date Performed] as date_performed,
  [Requested-Performed Time Lapse] as requested_performed_time_lapse,
  [Reported Date] as reported_date,
  [Performed-Reported Time Lapse] as performed_reported_time_lapse,
  [Biopsy Taken] collate SQL_Latin1_General_CP1_CI_AS as biopsy_taken,
  Outcome collate SQL_Latin1_General_CP1_CI_AS as outcome,
  cast(Comments as varchar(200)) collate SQL_Latin1_General_CP1_CI_AS as comments,
  [Reason Not Performed] collate SQL_Latin1_General_CP1_CI_AS as reason_not_performed,
  cast([Other Reason Not Performed] as varchar(200))
    collate SQL_Latin1_General_CP1_CI_AS as other_reason_not_performed,
  [Imaging Code(NICIP)] collate SQL_Latin1_General_CP1_CI_AS as imagine_code_nicip,
  [Imaging Code (SNOMed CT)] collate SQL_Latin1_General_CP1_CI_AS as imaging_code_snomed_ct,
  [Anatomical Site 1] collate SQL_Latin1_General_CP1_CI_AS as anatomical_site_1,
  [Anatomical Site 2] collate SQL_Latin1_General_CP1_CI_AS as anatomical_site_2,
  [Anatomical Site 3] collate SQL_Latin1_General_CP1_CI_AS as anatomical_site_3,
  [Anatomical Side] collate SQL_Latin1_General_CP1_CI_AS as anatomical_side,
  cast([Imaging Report Text] as varchar(200)) collate SQL_Latin1_General_CP1_CI_AS as imagine_report_text,
  [Primary Lesion Size] as primary_lesion_size,
  Radiologist collate SQL_Latin1_General_CP1_CI_AS as radiologist,
  [Platelet Count] as platelet_count,
  [HB Concentration] as hb_conc,
  [Bone Marrow Blasts (%)] as bone_marrow_blasts_pct,
  [Neutrophil Count] as neutrophil_count,
  [Albumin Level] as albumin_level,
  [Beta 2 Microglobulin] as beta_2_microglobulin,
  [Lymphocyte Count] as lymphocyte_count,
  [Blood Myeloblasts] as blood_myeloblasts,
  [Blood Basophils] as blood_basophils,
  [Blood Eosinophils] as blood_eosinophils,
  [% Predicted / FEV1] as pct_predicted_fev1,
  [Absolute Figure / FEV1] as absolute_fig_fev1,
  [Staging Laparoscopy Performed] collate SQL_Latin1_General_CP1_CI_AS as staging_laparoscopy_performed,
  FBC collate SQL_Latin1_General_CP1_CI_AS as fbc,
  [U&E] collate SQL_Latin1_General_CP1_CI_AS as ue,
  LFT collate SQL_Latin1_General_CP1_CI_AS as lft,
  ECG collate SQL_Latin1_General_CP1_CI_AS as ecg,
  [Group Save] collate SQL_Latin1_General_CP1_CI_AS as group_save,
  [X Match] collate SQL_Latin1_General_CP1_CI_AS as x_match,
  Calcium collate SQL_Latin1_General_CP1_CI_AS as calcium,
  [CA 15-3] collate SQL_Latin1_General_CP1_CI_AS as ca_15_3,
  Other collate SQL_Latin1_General_CP1_CI_AS as other,
  [Radiological T Stage] collate SQL_Latin1_General_CP1_CI_AS as t_stage_radiological,
  [Radiological N Stage] collate SQL_Latin1_General_CP1_CI_AS as n_stage_radiological,
  [Radiological M Stage] collate SQL_Latin1_General_CP1_CI_AS as m_stage_radiological,
  getdate() as last_edit_time,
  getdate() as updated_at,
  'rxn' as org_code,
  'scr' as source_system
from @scr_db.dbo.BIvwInvestigations