
MODEL (
  name lth_bronze.src_scr__diagnosis,
  kind FULL,
  cron '@daily',
);

select
  care_id,
  cancer_site,
  nhs_number,
  mrn,
  patient_status,
  assessed_by,
  tumour_status,
  date_of_diagnosis,
  other_reason,
  date_of_new_referral,
  new_tumour_site,
  date_patient_informed,
  non_cancer_diagnosis_chapter,
  non_cancer_diagnosis_group,
  icd_primary_diagnosis,
  snomed_primary_diagnosis,
  secondary_diagnosis,
  laterality,
  non_cancer_details,
  organisation,
  basis_of_diagnosis,
  histology,
  grade_of_differentiation,
  date_referred_cns,
  date_first_seen_cns,
  other_tumour_site_primary_diagnosis,
  other_tumour_site_secondary_diagnosis,
  date_gp_infromed_of_diagnosis,
  gp_informed_of_diagnosis,
  spec_nurse_present_when_informed,
  relative_carer_informed,
  date_referred_tertiary_centre,
  organisation_tertiary_centre,
  reason_for_ref_tertiary_care,
  topography_icd03,
  primary_diag_subsidiary_comment,
  consultant_diagnosis,
  consultant_age_specialty_diagnosis,
  pathway_end_date_faster_diag,
  pathway_end_reason_faster_diag,
  exclusion_reason,
  faster_diagnosis_organisation,
  care_professional,
  method_of_communication,
  delay_reason,
  primary_cancer_site,
  last_edit_time,
  updated_at
from @catalog_src.@schema_src.src_scr__diagnosis
