
MODEL (
  name lth_bronze.src_scr__referrals,
  kind FULL,
  cron '@daily',
);

select
  care_id,
  patient_id_scr,
  cancer_site,
  subtype,
  nhs_number,
  mrn,
  source_of_referral,
  priority_type,
  referral_route,
  other_route,
  rapid_diagnostic_cancer_pathway,
  upgrade_date,
  referral_type,
  gp_code,
  gp_name,
  practice_code,
  branch_code,
  ccg,
  ccg_code,
  patient_status,
  date_decision_to_refer,
  date_receipt_of_referral,
  date_first_appointment,
  first_appt_offered,
  reason_no_appt,
  organsiation,
  cons_first_appt,
  initial_ref_appropriate_specialist,
  first_appt_type,
  date_referred_to_specialist,
  org_referred_from,
  date_first_appt_specialist,
  org_first_appt_specialist,
  consultant,
  specialty,
  nice_referring_symptoms,
  referring_symptoms,
  other_symptoms,
  method_of_referral,
  appropriateness_of_ref,
  reason_inappropriate,
  additional_comments,
  date_dna_appt_rebooked,
  adjustment_reason,
  waiting_time_adjust,
  delay_reason,
  delay_reason_comments,
  waiting_time_adj_dtt_days,
  adt_ref_id,
  ref_org,
  val_for_upload,
  last_edit_time,
  updated_at
from @catalog_src.@schema_src.src_scr__referrals
