
MODEL (
  name lth_bronze.src_scr__teletherapy,
  kind VIEW,
  cron '@daily',
);

select
   [CARE_ID] as care_id,
   [Cancer Site] collate SQL_Latin1_General_CP1_CI_AS as cancer_Site,
   [NHS Number] collate SQL_Latin1_General_CP1_CI_AS as nhs_number,
   [Hospital Number] collate SQL_Latin1_General_CP1_CI_AS as mrn,
   [Consultant] collate SQL_Latin1_General_CP1_CI_AS as consultant,
   [Priority] collate SQL_Latin1_General_CP1_CI_AS as priority,
   [Date Decision to Treat] as date_decision_to_treat,
   [Organisation (DTT)] collate SQL_Latin1_General_CP1_CI_AS as organisation_dtt,
   [Date Start of Treatment] as date_treatment_start,
   [Organisation (Treatment) Site Code] collate SQL_Latin1_General_CP1_CI_AS as organisation_site_code,
   [Organisation (Treatment) Name] collate SQL_Latin1_General_CP1_CI_AS as organisation_name,
   [Treatment Event Type] collate SQL_Latin1_General_CP1_CI_AS as treatment_event_type,
   [Treatment Setting] collate SQL_Latin1_General_CP1_CI_AS as treatment_setting,
   [Clinical Trial] collate SQL_Latin1_General_CP1_CI_AS as clinical_trial,
   [Treatment Intent] collate SQL_Latin1_General_CP1_CI_AS as treatment_intent,
   [Adjunctive Therapy] collate SQL_Latin1_General_CP1_CI_AS as adjunctive_therapy,
   [Short/Long Course] collate SQL_Latin1_General_CP1_CI_AS as short_long_course,
   [Chemo-Radiotherapy] collate SQL_Latin1_General_CP1_CI_AS as chemo_radiotherapy,
   [Beam Quality] collate SQL_Latin1_General_CP1_CI_AS as beam_quality,
   [Treatment Site] collate SQL_Latin1_General_CP1_CI_AS as treatment_site,
   [Anatomical Site] collate SQL_Latin1_General_CP1_CI_AS as anatomical_site,
   [Complexity Group] collate SQL_Latin1_General_CP1_CI_AS as complexity_group,
   [Anaesthetic Required] collate SQL_Latin1_General_CP1_CI_AS as anaesthetic_required,
   [Fields] collate SQL_Latin1_General_CP1_CI_AS as fields,
   [Multiple Planning] collate SQL_Latin1_General_CP1_CI_AS as multipla_planning,
   [Prescribed Dose (Gy)] as prescribed_dose,
   [Dose per Fraction] as dose_per_fraction,
   [Prescribed Fractions] as prescribed_fractions,
   [Fraction per Week] as fraction_per_week,
   [Prescribed Duration] as prescribed_duration,
   [Actual Dose (Gy)] as actual_dose,
   [Actual Duration] as actual_duration,
   [Actual Fractions] as actual_fractions,
   [Treatment Outcome] collate SQL_Latin1_General_CP1_CI_AS as treatment_outcome,
   [Radio Surgery Performed Indicator] collate SQL_Latin1_General_CP1_CI_AS as radio_surgery_performed_indicator,
   [End Date] as end_date,
   getdate() as last_edit_time,
   getdate() as updated_at,
  'rxn' collate SQL_Latin1_General_CP1_CI_AS as org_code,
  'scr' collate SQL_Latin1_General_CP1_CI_AS as source_system
from @scr_db.dbo.BIvwTreatmentTeletherapy
