
MODEL (
  name lth_bronze.src_scr__diagnosis,
  kind VIEW,
  cron '@daily',
);

select
  CARE_ID as care_id,
  [Cancer Site] collate SQL_Latin1_General_CP1_CI_AS as cancer_site,
  [NHS Number] collate SQL_Latin1_General_CP1_CI_AS as nhs_number,
  [Hospital Number] collate SQL_Latin1_General_CP1_CI_AS as mrn,
  [Patient Status] collate SQL_Latin1_General_CP1_CI_AS as patient_status,
  [Assessed By] collate SQL_Latin1_General_CP1_CI_AS as assessed_by,
  [Tumour Status] collate SQL_Latin1_General_CP1_CI_AS as tumour_status,
  [Date of Diagnosis] as date_of_diagnosis,
  [Other Reason] collate SQL_Latin1_General_CP1_CI_AS as other_reason,
  [Date of New Referral] as date_of_new_referral,
  [New Tumour Site] collate SQL_Latin1_General_CP1_CI_AS as new_tumour_site,
  [Date Patient Informed] as date_patient_informed,
  [Non-cancer Diagnosis (Chapter)] collate SQL_Latin1_General_CP1_CI_AS as non_cancer_diagnosis_chapter,
  [Non-Cancer Diagnosis (Group)] collate SQL_Latin1_General_CP1_CI_AS as non_cancer_diagnosis_group,
  [Primary Diagnosis (ICD)] collate SQL_Latin1_General_CP1_CI_AS as icd_primary_diagnosis,
  [Primary Diagnosis (SNOMED)] collate SQL_Latin1_General_CP1_CI_AS as snomed_primary_diagnosis,
  [Secondary Diagnosis] collate SQL_Latin1_General_CP1_CI_AS as secondary_diagnosis,
  Laterality  collate SQL_Latin1_General_CP1_CI_AS as laterality,
  [Non-cancer details] collate SQL_Latin1_General_CP1_CI_AS as non_cancer_details,
  Organisation collate SQL_Latin1_General_CP1_CI_AS as organisation,
  [Basis of Diagnosis] collate SQL_Latin1_General_CP1_CI_AS as basis_of_diagnosis,
  Histology collate SQL_Latin1_General_CP1_CI_AS as histology,
  [Grade of Differentiation] collate SQL_Latin1_General_CP1_CI_AS as grade_of_differentiation,
  [Date Referred to CNS] as date_referred_cns,
  [Date First Seen by CNS] as date_first_seen_cns,
  [Other Tumour Site Primary Diagnosis] collate SQL_Latin1_General_CP1_CI_AS as other_tumour_site_primary_diagnosis,
  [Other Tumour Site Secondary Diagnosis] collate SQL_Latin1_General_CP1_CI_AS
    as other_tumour_site_secondary_diagnosis,
  [Date GP Informed of Diagnosis] as date_gp_infromed_of_diagnosis,
  [GP Informed of Diagnosis] collate SQL_Latin1_General_CP1_CI_AS as gp_informed_of_diagnosis,
  [Spec Nurse Present when Pt Informed] collate SQL_Latin1_General_CP1_CI_AS as spec_nurse_present_when_informed,
  [Relative/Carer Informed of Diagnosis] collate SQL_Latin1_General_CP1_CI_AS as relative_carer_informed,
  [Date Referred (Tertiary Centre)] as date_referred_tertiary_centre,
  [Organisation (Tertiary Centre)] collate SQL_Latin1_General_CP1_CI_AS as organisation_tertiary_centre,
  [Reason for Referral (Tertiary Centre)] collate SQL_Latin1_General_CP1_CI_AS as reason_for_ref_tertiary_care,
  [Topography ICD03] collate SQL_Latin1_General_CP1_CI_AS as topography_icd03,
  [Primary Diagnosis Subsidiary Comment] collate SQL_Latin1_General_CP1_CI_AS as primary_diag_subsidiary_comment,
  [Consultant (at diagnosis)] collate SQL_Latin1_General_CP1_CI_AS as consultant_diagnosis,
  [Consultant Age Specialty (at diagnosis)]  collate SQL_Latin1_General_CP1_CI_AS
    as consultant_age_specialty_diagnosis,
  [Pathway End Date (Faster Diagnosis)] as pathway_end_date_faster_diag,
  [Pathway End Reason (Faster Diagnosis)] collate SQL_Latin1_General_CP1_CI_AS as pathway_end_reason_faster_diag,
  [Exclusion Reason] collate SQL_Latin1_General_CP1_CI_AS as exclusion_reason,
  [Faster Diagnosis Organisation] collate SQL_Latin1_General_CP1_CI_AS as faster_diagnosis_organisation,
  [Care Professional] collate SQL_Latin1_General_CP1_CI_AS as care_professional,
  [Method of Communication] collate SQL_Latin1_General_CP1_CI_AS as method_of_communication,
  [Delay Reason] collate SQL_Latin1_General_CP1_CI_AS as delay_reason,
  [Primary Cancer Site] collate SQL_Latin1_General_CP1_CI_AS as primary_cancer_site,
  getdate() as last_edit_time,
  getdate() as updated_at, 
  'rxn' collate SQL_Latin1_General_CP1_CI_AS as org_code,
  'scr' collate SQL_Latin1_General_CP1_CI_AS as source_system
from @scr_db.dbo.BIvwDiagnosis
