
MODEL (
  name lth_bronze.src_scr__pathology,
  kind VIEW,
  cron '@daily',
);

select
  CARE_ID as care_id,
  [Cancer Site] collate SQL_Latin1_General_CP1_CI_AS as cancer_site,
  [NHS Number] collate SQL_Latin1_General_CP1_CI_AS as nhs_number,
  [Hospital Number] collate SQL_Latin1_General_CP1_CI_AS as mrn,
  [Date of Receipt] as receipt_date,
  [Date of Reporting] as reporting_date,
  [Report No] collate SQL_Latin1_General_CP1_CI_AS as report_number,
  [Investigation Type] collate SQL_Latin1_General_CP1_CI_AS as investigation_type,
  [Nature of Specimen] collate SQL_Latin1_General_CP1_CI_AS as nature_of_specimen,
  [Report Status] collate SQL_Latin1_General_CP1_CI_AS as report_status,
  Surgeon collate SQL_Latin1_General_CP1_CI_AS as surgeon,
  [Requesting Organisation] collate SQL_Latin1_General_CP1_CI_AS as requesting_organisation,
  Pathologist collate SQL_Latin1_General_CP1_CI_AS as pathologist,
  [Reporting Organisation] collate SQL_Latin1_General_CP1_CI_AS as reporting_organisation,
  [Diagnosis Site (ICD)] collate SQL_Latin1_General_CP1_CI_AS as diagnosis_site_icd,
  [Diagnosis Site (SNOMED)] collate SQL_Latin1_General_CP1_CI_AS as diagnosis_site_snomed,
  Laterality collate SQL_Latin1_General_CP1_CI_AS as laterality,
  [Max Tumour Diameter (mm)] as max_tumour_diameter_mm,
  [No of Nodes Examined] as num_nodes_examined,
  [No of Positive Nodes] as num_pos_nodes,
  [Type (SNOMed)] collate SQL_Latin1_General_CP1_CI_AS as type_snomed,
  [Grade of Differentiation] collate SQL_Latin1_General_CP1_CI_AS as grade_differentiation,
  [Excision Margins] collate SQL_Latin1_General_CP1_CI_AS as excision_margins,
  [Vascular/Lymphatic Invasion] collate SQL_Latin1_General_CP1_CI_AS as vascular_lymphatic_invasion,
  [Synchronous Tumour] collate SQL_Latin1_General_CP1_CI_AS as synchronous_tumour,
  [Pathological Staging] collate SQL_Latin1_General_CP1_CI_AS as pathological_staging,
  cast(Comments collate SQL_Latin1_General_CP1_CI_AS as varchar(200)) as comments,
  getdate() as last_edit_time,
  getdate() as updated_at,
  'rxn' collate SQL_Latin1_General_CP1_CI_AS as org_code,
  'scr' collate SQL_Latin1_General_CP1_CI_AS as source_system
from @scr_db.dbo.BIvwPathology
